import type { Metadata } from 'next';
import './globals.css';
import { NavLinks } from './ui/nav-links';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavLinks />
        <div>{auth}</div>
        <main>{children}</main>
      </body>
    </html>
  );
}
